package zhao.blog.managementsystem.entity;
// Generated 2017-9-5 11:47:22 by Hibernate Tools 4.0.0.Final
import java.util.HashSet;
import java.util.Set;

/**
 * BlogUser generated by hbm2java
 */
public class BlogUser implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userAcc;
	private String userPwd;
	private String userPhone;
	private String userSex;
	private String userQq;
	private String userEmail;
	private String userAddress;
	private String userBirthday;
	private String userDescription;
	private String userImageUrl;
	private String userRegisterTime;
	private Set blogCritiques = new HashSet(0);
	private Set blogDailies = new HashSet(0);
	private Set blogArticles = new HashSet(0);
	private Set blogAlbums = new HashSet(0);
	private Set blogPhotos = new HashSet(0);
	
	public BlogUser() {
		super();
	}

	public BlogUser(Integer userId, String userName, String userAcc, String userPwd, String userPhone, String userSex,
			String userQq, String userEmail, String userAddress, String userBirthday, String userDescription,
			String userImageUrl, String userRegisterTime) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.userAcc = userAcc;
		this.userPwd = userPwd;
		this.userPhone = userPhone;
		this.userSex = userSex;
		this.userQq = userQq;
		this.userEmail = userEmail;
		this.userAddress = userAddress;
		this.userBirthday = userBirthday;
		this.userDescription = userDescription;
		this.userImageUrl = userImageUrl;
		this.userRegisterTime = userRegisterTime;
	}

	public BlogUser(Integer userId, String userName, String userAcc, String userPwd, String userPhone, String userSex,
			String userQq, String userEmail, String userAddress, String userBirthday, String userDescription,
			String userImageUrl, String userRegisterTime, Set blogCritiques, Set blogDailies, Set blogArticles,
			Set blogAlbums, Set blogPhotos) {
		super();
		this.userId = userId;
		this.userName = userName;
		this.userAcc = userAcc;
		this.userPwd = userPwd;
		this.userPhone = userPhone;
		this.userSex = userSex;
		this.userQq = userQq;
		this.userEmail = userEmail;
		this.userAddress = userAddress;
		this.userBirthday = userBirthday;
		this.userDescription = userDescription;
		this.userImageUrl = userImageUrl;
		this.userRegisterTime = userRegisterTime;
		this.blogCritiques = blogCritiques;
		this.blogDailies = blogDailies;
		this.blogArticles = blogArticles;
		this.blogAlbums = blogAlbums;
		this.blogPhotos = blogPhotos;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserAcc() {
		return userAcc;
	}

	public void setUserAcc(String userAcc) {
		this.userAcc = userAcc;
	}

	public String getUserPwd() {
		return userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public String getUserPhone() {
		return userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	public String getUserSex() {
		return userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	public String getUserQq() {
		return userQq;
	}

	public void setUserQq(String userQq) {
		this.userQq = userQq;
	}

	public String getUserEmail() {
		return userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserAddress() {
		return userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	public String getUserBirthday() {
		return userBirthday;
	}

	public void setUserBirthday(String userBirthday) {
		this.userBirthday = userBirthday;
	}

	public String getUserDescription() {
		return userDescription;
	}

	public void setUserDescription(String userDescription) {
		this.userDescription = userDescription;
	}

	public String getUserImageUrl() {
		return userImageUrl;
	}

	public void setUserImageUrl(String userImageUrl) {
		this.userImageUrl = userImageUrl;
	}

	public String getUserRegisterTime() {
		return userRegisterTime;
	}

	public void setUserRegisterTime(String userRegisterTime) {
		this.userRegisterTime = userRegisterTime;
	}

	public Set getBlogCritiques() {
		return blogCritiques;
	}

	public void setBlogCritiques(Set blogCritiques) {
		this.blogCritiques = blogCritiques;
	}

	public Set getBlogDailies() {
		return blogDailies;
	}

	public void setBlogDailies(Set blogDailies) {
		this.blogDailies = blogDailies;
	}

	public Set getBlogArticles() {
		return blogArticles;
	}

	public void setBlogArticles(Set blogArticles) {
		this.blogArticles = blogArticles;
	}

	public Set getBlogAlbums() {
		return blogAlbums;
	}

	public void setBlogAlbums(Set blogAlbums) {
		this.blogAlbums = blogAlbums;
	}

	public Set getBlogPhotos() {
		return blogPhotos;
	}

	public void setBlogPhotos(Set blogPhotos) {
		this.blogPhotos = blogPhotos;
	}

	

}
