package zhao.blog.managementsystem.entity;
// Generated 2017-9-5 11:47:22 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * BlogCritique generated by hbm2java
 */
public class BlogCritique implements java.io.Serializable {

	private Integer replyId;
	private BlogUser blogUser;
	private BlogCritique blogCritique;
	private String replyContent;
	private int replyTypeId;
	private byte replyType;
	private String replyTime;
	private Set blogCritiques = new HashSet(0);

	public BlogCritique() {
	}

	public BlogCritique(BlogUser blogUser, BlogCritique blogCritique, String replyContent, int replyTypeId,
			byte replyType, String replyTime) {
		this.blogUser = blogUser;
		this.blogCritique = blogCritique;
		this.replyContent = replyContent;
		this.replyTypeId = replyTypeId;
		this.replyType = replyType;
		this.replyTime = replyTime;
	}

	public BlogCritique(BlogUser blogUser, BlogCritique blogCritique, String replyContent, int replyTypeId,
			byte replyType, String replyTime, Set blogCritiques) {
		this.blogUser = blogUser;
		this.blogCritique = blogCritique;
		this.replyContent = replyContent;
		this.replyTypeId = replyTypeId;
		this.replyType = replyType;
		this.replyTime = replyTime;
		this.blogCritiques = blogCritiques;
	}

	public Integer getReplyId() {
		return this.replyId;
	}

	public void setReplyId(Integer replyId) {
		this.replyId = replyId;
	}

	public BlogUser getBlogUser() {
		return this.blogUser;
	}

	public void setBlogUser(BlogUser blogUser) {
		this.blogUser = blogUser;
	}

	public BlogCritique getBlogCritique() {
		return this.blogCritique;
	}

	public void setBlogCritique(BlogCritique blogCritique) {
		this.blogCritique = blogCritique;
	}

	public String getReplyContent() {
		return this.replyContent;
	}

	public void setReplyContent(String replyContent) {
		this.replyContent = replyContent;
	}

	public int getReplyTypeId() {
		return this.replyTypeId;
	}

	public void setReplyTypeId(int replyTypeId) {
		this.replyTypeId = replyTypeId;
	}

	public byte getReplyType() {
		return this.replyType;
	}

	public void setReplyType(byte replyType) {
		this.replyType = replyType;
	}

	public String getReplyTime() {
		return this.replyTime;
	}

	public void setReplyTime(String replyTime) {
		this.replyTime = replyTime;
	}

	public Set getBlogCritiques() {
		return this.blogCritiques;
	}

	public void setBlogCritiques(Set blogCritiques) {
		this.blogCritiques = blogCritiques;
	}

}
