package zhao.blog.managementsystem.entity;
// Generated 2017-9-5 11:47:22 by Hibernate Tools 4.0.0.Final

/**
 * BlogDaily generated by hbm2java
 */
public class BlogDaily implements java.io.Serializable {

	private Integer dailyId;
	private BlogUser blogUser;
	private String dailyContent;
	private String dailyTime;

	public BlogDaily() {
	}

	public BlogDaily(Integer dailyId, BlogUser blogUser, String dailyContent, String dailyTime) {
		super();
		this.dailyId = dailyId;
		this.blogUser = blogUser;
		this.dailyContent = dailyContent;
		this.dailyTime = dailyTime;
	}

	public Integer getDailyId() {
		return dailyId;
	}

	public void setDailyId(Integer dailyId) {
		this.dailyId = dailyId;
	}

	public BlogUser getBlogUser() {
		return blogUser;
	}

	public void setBlogUser(BlogUser blogUser) {
		this.blogUser = blogUser;
	}

	public String getDailyContent() {
		return dailyContent;
	}

	public void setDailyContent(String dailyContent) {
		this.dailyContent = dailyContent;
	}

	public String getDailyTime() {
		return dailyTime;
	}

	public void setDailyTime(String dailyTime) {
		this.dailyTime = dailyTime;
	}

	
}
