package zhao.blog.managementsystem.entity;
// Generated 2017-9-5 11:47:22 by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * BlogSortArticle generated by hbm2java
 */
public class BlogSortArticle implements java.io.Serializable {

	private Integer sortArticleId;
	private String sortArticleName;
	private Set blogArticles = new HashSet(0);

	public BlogSortArticle() {
	}

	public BlogSortArticle(String sortArticleName) {
		this.sortArticleName = sortArticleName;
	}

	public BlogSortArticle(String sortArticleName, Set blogArticles) {
		this.sortArticleName = sortArticleName;
		this.blogArticles = blogArticles;
	}

	public Integer getSortArticleId() {
		return this.sortArticleId;
	}

	public void setSortArticleId(Integer sortArticleId) {
		this.sortArticleId = sortArticleId;
	}

	public String getSortArticleName() {
		return this.sortArticleName;
	}

	public void setSortArticleName(String sortArticleName) {
		this.sortArticleName = sortArticleName;
	}

	public Set getBlogArticles() {
		return this.blogArticles;
	}

	public void setBlogArticles(Set blogArticles) {
		this.blogArticles = blogArticles;
	}

}
