package zhao.blog.managementsystem.entity;
// Generated 2017-9-5 11:47:22 by Hibernate Tools 4.0.0.Final

/**
 * BlogPhoto generated by hbm2java
 */
public class BlogPhoto implements java.io.Serializable {

	private Integer photoId;
	private BlogAlbum blogAlbum;
	private BlogUser blogUser;
	private String photoName;
	private String photoSrc;
	private String photoDescription;
	private String photoTime;

	public BlogPhoto() {
	}

	public BlogPhoto(BlogAlbum blogAlbum, BlogUser blogUser, String photoName, String photoSrc, String photoDescription,
			String photoTime) {
		this.blogAlbum = blogAlbum;
		this.blogUser = blogUser;
		this.photoName = photoName;
		this.photoSrc = photoSrc;
		this.photoDescription = photoDescription;
		this.photoTime = photoTime;
	}

	public Integer getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(Integer photoId) {
		this.photoId = photoId;
	}

	public BlogAlbum getBlogAlbum() {
		return this.blogAlbum;
	}

	public void setBlogAlbum(BlogAlbum blogAlbum) {
		this.blogAlbum = blogAlbum;
	}

	public BlogUser getBlogUser() {
		return this.blogUser;
	}

	public void setBlogUser(BlogUser blogUser) {
		this.blogUser = blogUser;
	}

	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	public String getPhotoSrc() {
		return this.photoSrc;
	}

	public void setPhotoSrc(String photoSrc) {
		this.photoSrc = photoSrc;
	}

	public String getPhotoDescription() {
		return this.photoDescription;
	}

	public void setPhotoDescription(String photoDescription) {
		this.photoDescription = photoDescription;
	}

	public String getPhotoTime() {
		return this.photoTime;
	}

	public void setPhotoTime(String photoTime) {
		this.photoTime = photoTime;
	}

}
