package zhao.blog.managementsystem.entity;
// Generated 2017-9-5 11:47:22 by Hibernate Tools 4.0.0.Final

/**
 * BlogArticle generated by hbm2java
 */
public class BlogArticle implements java.io.Serializable,Cloneable {

	private Integer articleId;
	private BlogSortArticle blogSortArticle;
	private BlogUser blogUser;
	private String articleTitle;
	private String articleTime;
	private int articleClick;
	private String articlePic;
	private String articleContent;
	private byte articleUp;
	private byte articleSupport;
	private String articleDescript;

	public BlogArticle() {
	}

	public BlogArticle(Integer articleId, BlogSortArticle blogSortArticle, BlogUser blogUser, String articleTitle,
			String articleTime, int articleClick, String articlePic, String articleContent, byte articleUp,
			byte articleSupport, String articleDescript) {
		super();
		this.articleId = articleId;
		this.blogSortArticle = blogSortArticle;
		this.blogUser = blogUser;
		this.articleTitle = articleTitle;
		this.articleTime = articleTime;
		this.articleClick = articleClick;
		this.articlePic = articlePic;
		this.articleContent = articleContent;
		this.articleUp = articleUp;
		this.articleSupport = articleSupport;
		this.articleDescript = articleDescript;
	}

	public Integer getArticleId() {
		return articleId;
	}

	public void setArticleId(Integer articleId) {
		this.articleId = articleId;
	}

	public BlogSortArticle getBlogSortArticle() {
		return blogSortArticle;
	}

	public void setBlogSortArticle(BlogSortArticle blogSortArticle) {
		this.blogSortArticle = blogSortArticle;
	}

	public BlogUser getBlogUser() {
		return blogUser;
	}

	public void setBlogUser(BlogUser blogUser) {
		this.blogUser = blogUser;
	}

	public String getArticleTitle() {
		return articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	public String getArticleTime() {
		return articleTime;
	}

	public void setArticleTime(String articleTime) {
		this.articleTime = articleTime;
	}

	public int getArticleClick() {
		return articleClick;
	}

	public void setArticleClick(int articleClick) {
		this.articleClick = articleClick;
	}

	public String getArticlePic() {
		return articlePic;
	}

	public void setArticlePic(String articlePic) {
		this.articlePic = articlePic;
	}

	public String getArticleContent() {
		return articleContent;
	}

	public void setArticleContent(String articleContent) {
		this.articleContent = articleContent;
	}

	public byte getArticleUp() {
		return articleUp;
	}

	public void setArticleUp(byte articleUp) {
		this.articleUp = articleUp;
	}

	public byte getArticleSupport() {
		return articleSupport;
	}

	public void setArticleSupport(byte articleSupport) {
		this.articleSupport = articleSupport;
	}

	public String getArticleDescript() {
		return articleDescript;
	}

	public void setArticleDescript(String articleDescript) {
		this.articleDescript = articleDescript;
	}

	
}
